// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/events.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====== Models ======
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	IntervalDays  int32                  `protobuf:"varint,5,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	StopAt        *string                `protobuf:"bytes,6,opt,name=stop_at,json=stopAt,proto3,oneof" json:"stop_at,omitempty"` // -> Option<String>
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Event) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

func (x *Event) GetStopAt() string {
	if x != nil && x.StopAt != nil {
		return *x.StopAt
	}
	return ""
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ====== CRUD ======
type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	IntervalDays  int32                  `protobuf:"varint,4,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	StopAt        *string                `protobuf:"bytes,5,opt,name=stop_at,json=stopAt,proto3,oneof" json:"stop_at,omitempty"` // -> Option<String>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateEventRequest) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

func (x *CreateEventRequest) GetStopAt() string {
	if x != nil && x.StopAt != nil {
		return *x.StopAt
	}
	return ""
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type UpdateEventRequest struct {
	state        protoimpl.MessageState  `protogen:"open.v1"`
	CustomerId   string                  `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Id           string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                            // presence = patch
	StartDate    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	IntervalDays *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	// tri-state para stop_at (igual ao teu Option<Option<...>>):
	//
	// Types that are valid to be assigned to StopAtChange:
	//
	//	*UpdateEventRequest_StopAt
	//	*UpdateEventRequest_ClearStopAt
	StopAtChange  isUpdateEventRequest_StopAtChange `protobuf_oneof:"stop_at_change"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateEventRequest) GetStartDate() *wrapperspb.StringValue {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateEventRequest) GetIntervalDays() *wrapperspb.Int32Value {
	if x != nil {
		return x.IntervalDays
	}
	return nil
}

func (x *UpdateEventRequest) GetStopAtChange() isUpdateEventRequest_StopAtChange {
	if x != nil {
		return x.StopAtChange
	}
	return nil
}

func (x *UpdateEventRequest) GetStopAt() string {
	if x != nil {
		if x, ok := x.StopAtChange.(*UpdateEventRequest_StopAt); ok {
			return x.StopAt
		}
	}
	return ""
}

func (x *UpdateEventRequest) GetClearStopAt() bool {
	if x != nil {
		if x, ok := x.StopAtChange.(*UpdateEventRequest_ClearStopAt); ok {
			return x.ClearStopAt
		}
	}
	return false
}

type isUpdateEventRequest_StopAtChange interface {
	isUpdateEventRequest_StopAtChange()
}

type UpdateEventRequest_StopAt struct {
	StopAt string `protobuf:"bytes,6,opt,name=stop_at,json=stopAt,proto3,oneof"` // define data
}

type UpdateEventRequest_ClearStopAt struct {
	ClearStopAt bool `protobuf:"varint,7,opt,name=clear_stop_at,json=clearStopAt,proto3,oneof"` // true => seta NULL
}

func (*UpdateEventRequest_StopAt) isUpdateEventRequest_StopAtChange() {}

func (*UpdateEventRequest_ClearStopAt) isUpdateEventRequest_StopAtChange() {}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type CutEventFromRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutEventFromRequest) Reset() {
	*x = CutEventFromRequest{}
	mi := &file_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutEventFromRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutEventFromRequest) ProtoMessage() {}

func (x *CutEventFromRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutEventFromRequest.ProtoReflect.Descriptor instead.
func (*CutEventFromRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *CutEventFromRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CutEventFromRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CutEventFromRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

// ====== Occurrences ======
type ListOccurrencesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CustomerId    string                  `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Start         string                  `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"` // YYYY-MM-DD
	End           string                  `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`     // YYYY-MM-DD
	Name          *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`   // filtro opcional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOccurrencesRequest) Reset() {
	*x = ListOccurrencesRequest{}
	mi := &file_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOccurrencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOccurrencesRequest) ProtoMessage() {}

func (x *ListOccurrencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOccurrencesRequest.ProtoReflect.Descriptor instead.
func (*ListOccurrencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *ListOccurrencesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListOccurrencesRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *ListOccurrencesRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *ListOccurrencesRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

type Occurrence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Occurrence) Reset() {
	*x = Occurrence{}
	mi := &file_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Occurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occurrence) ProtoMessage() {}

func (x *Occurrence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occurrence.ProtoReflect.Descriptor instead.
func (*Occurrence) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *Occurrence) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Occurrence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Occurrence) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ListOccurrencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Occurrences   []*Occurrence          `protobuf:"bytes,3,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOccurrencesResponse) Reset() {
	*x = ListOccurrencesResponse{}
	mi := &file_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOccurrencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOccurrencesResponse) ProtoMessage() {}

func (x *ListOccurrencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOccurrencesResponse.ProtoReflect.Descriptor instead.
func (*ListOccurrencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *ListOccurrencesResponse) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *ListOccurrencesResponse) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *ListOccurrencesResponse) GetOccurrences() []*Occurrence {
	if x != nil {
		return x.Occurrences
	}
	return nil
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\x10gobizz.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb0\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12#\n" +
	"\rinterval_days\x18\x05 \x01(\x05R\fintervalDays\x12\x1c\n" +
	"\astop_at\x18\x06 \x01(\tH\x00R\x06stopAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_stop_at\"\xb7\x01\n" +
	"\x12CreateEventRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12#\n" +
	"\rinterval_days\x18\x04 \x01(\x05R\fintervalDays\x12\x1c\n" +
	"\astop_at\x18\x05 \x01(\tH\x00R\x06stopAt\x88\x01\x01B\n" +
	"\n" +
	"\b_stop_at\"B\n" +
	"\x0fGetEventRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"b\n" +
	"\x11ListEventsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"E\n" +
	"\x12ListEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.gobizz.events.v1.EventR\x06events\"\xc9\x02\n" +
	"\x12UpdateEventRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x120\n" +
	"\x04name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12;\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\tstartDate\x12@\n" +
	"\rinterval_days\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\fintervalDays\x12\x19\n" +
	"\astop_at\x18\x06 \x01(\tH\x00R\x06stopAt\x12$\n" +
	"\rclear_stop_at\x18\a \x01(\bH\x00R\vclearStopAtB\x10\n" +
	"\x0estop_at_change\"E\n" +
	"\x12DeleteEventRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"Z\n" +
	"\x13CutEventFromRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\"\x93\x01\n" +
	"\x16ListOccurrencesRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\x120\n" +
	"\x04name\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\"O\n" +
	"\n" +
	"Occurrence\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"\x81\x01\n" +
	"\x17ListOccurrencesResponse\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12>\n" +
	"\voccurrences\x18\x03 \x03(\v2\x1c.gobizz.events.v1.OccurrenceR\voccurrences2\xd9\x04\n" +
	"\x06Events\x12L\n" +
	"\vCreateEvent\x12$.gobizz.events.v1.CreateEventRequest\x1a\x17.gobizz.events.v1.Event\x12F\n" +
	"\bGetEvent\x12!.gobizz.events.v1.GetEventRequest\x1a\x17.gobizz.events.v1.Event\x12W\n" +
	"\n" +
	"ListEvents\x12#.gobizz.events.v1.ListEventsRequest\x1a$.gobizz.events.v1.ListEventsResponse\x12L\n" +
	"\vUpdateEvent\x12$.gobizz.events.v1.UpdateEventRequest\x1a\x17.gobizz.events.v1.Event\x12Z\n" +
	"\vDeleteEvent\x12$.gobizz.events.v1.DeleteEventRequest\x1a%.gobizz.events.v1.DeleteEventResponse\x12N\n" +
	"\fCutEventFrom\x12%.gobizz.events.v1.CutEventFromRequest\x1a\x17.gobizz.events.v1.Event\x12f\n" +
	"\x0fListOccurrences\x12(.gobizz.events.v1.ListOccurrencesRequest\x1a).gobizz.events.v1.ListOccurrencesResponseB\x16Z\x14events-service/protob\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_events_proto_goTypes = []any{
	(*Event)(nil),                   // 0: gobizz.events.v1.Event
	(*CreateEventRequest)(nil),      // 1: gobizz.events.v1.CreateEventRequest
	(*GetEventRequest)(nil),         // 2: gobizz.events.v1.GetEventRequest
	(*ListEventsRequest)(nil),       // 3: gobizz.events.v1.ListEventsRequest
	(*ListEventsResponse)(nil),      // 4: gobizz.events.v1.ListEventsResponse
	(*UpdateEventRequest)(nil),      // 5: gobizz.events.v1.UpdateEventRequest
	(*DeleteEventRequest)(nil),      // 6: gobizz.events.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),     // 7: gobizz.events.v1.DeleteEventResponse
	(*CutEventFromRequest)(nil),     // 8: gobizz.events.v1.CutEventFromRequest
	(*ListOccurrencesRequest)(nil),  // 9: gobizz.events.v1.ListOccurrencesRequest
	(*Occurrence)(nil),              // 10: gobizz.events.v1.Occurrence
	(*ListOccurrencesResponse)(nil), // 11: gobizz.events.v1.ListOccurrencesResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),  // 13: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),   // 14: google.protobuf.Int32Value
}
var file_proto_events_proto_depIdxs = []int32{
	12, // 0: gobizz.events.v1.Event.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: gobizz.events.v1.Event.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: gobizz.events.v1.ListEventsResponse.events:type_name -> gobizz.events.v1.Event
	13, // 3: gobizz.events.v1.UpdateEventRequest.name:type_name -> google.protobuf.StringValue
	13, // 4: gobizz.events.v1.UpdateEventRequest.start_date:type_name -> google.protobuf.StringValue
	14, // 5: gobizz.events.v1.UpdateEventRequest.interval_days:type_name -> google.protobuf.Int32Value
	13, // 6: gobizz.events.v1.ListOccurrencesRequest.name:type_name -> google.protobuf.StringValue
	10, // 7: gobizz.events.v1.ListOccurrencesResponse.occurrences:type_name -> gobizz.events.v1.Occurrence
	1,  // 8: gobizz.events.v1.Events.CreateEvent:input_type -> gobizz.events.v1.CreateEventRequest
	2,  // 9: gobizz.events.v1.Events.GetEvent:input_type -> gobizz.events.v1.GetEventRequest
	3,  // 10: gobizz.events.v1.Events.ListEvents:input_type -> gobizz.events.v1.ListEventsRequest
	5,  // 11: gobizz.events.v1.Events.UpdateEvent:input_type -> gobizz.events.v1.UpdateEventRequest
	6,  // 12: gobizz.events.v1.Events.DeleteEvent:input_type -> gobizz.events.v1.DeleteEventRequest
	8,  // 13: gobizz.events.v1.Events.CutEventFrom:input_type -> gobizz.events.v1.CutEventFromRequest
	9,  // 14: gobizz.events.v1.Events.ListOccurrences:input_type -> gobizz.events.v1.ListOccurrencesRequest
	0,  // 15: gobizz.events.v1.Events.CreateEvent:output_type -> gobizz.events.v1.Event
	0,  // 16: gobizz.events.v1.Events.GetEvent:output_type -> gobizz.events.v1.Event
	4,  // 17: gobizz.events.v1.Events.ListEvents:output_type -> gobizz.events.v1.ListEventsResponse
	0,  // 18: gobizz.events.v1.Events.UpdateEvent:output_type -> gobizz.events.v1.Event
	7,  // 19: gobizz.events.v1.Events.DeleteEvent:output_type -> gobizz.events.v1.DeleteEventResponse
	0,  // 20: gobizz.events.v1.Events.CutEventFrom:output_type -> gobizz.events.v1.Event
	11, // 21: gobizz.events.v1.Events.ListOccurrences:output_type -> gobizz.events.v1.ListOccurrencesResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	file_proto_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[5].OneofWrappers = []any{
		(*UpdateEventRequest_StopAt)(nil),
		(*UpdateEventRequest_ClearStopAt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
