// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/links_write.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl    string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,2,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	CustomerId     string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_proto_links_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *CreateLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateLinkRequest) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type CreateLinkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,3,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,4,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId     string                 `protobuf:"bytes,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,8,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_proto_links_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateLinkResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *CreateLinkResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *CreateLinkResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateLinkResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateLinkResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateLinkResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_proto_links_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_proto_links_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,5,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_proto_links_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *UpdateLinkRequest) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type UpdateLinkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId     string                 `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,9,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkResponse) Reset() {
	*x = UpdateLinkResponse{}
	mi := &file_proto_links_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkResponse) ProtoMessage() {}

func (x *UpdateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UpdateLinkResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *UpdateLinkResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *UpdateLinkResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateLinkResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateLinkResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateLinkResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type UpdateLinkClicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkClicksRequest) Reset() {
	*x = UpdateLinkClicksRequest{}
	mi := &file_proto_links_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkClicksRequest) ProtoMessage() {}

func (x *UpdateLinkClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkClicksRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkClicksRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLinkClicksRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateLinkClicksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId     string                 `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,9,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkClicksResponse) Reset() {
	*x = UpdateLinkClicksResponse{}
	mi := &file_proto_links_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkClicksResponse) ProtoMessage() {}

func (x *UpdateLinkClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkClicksResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkClicksResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_write_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLinkClicksResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *UpdateLinkClicksResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

var File_proto_links_write_proto protoreflect.FileDescriptor

const file_proto_links_write_proto_rawDesc = "" +
	"\n" +
	"\x17proto/links_write.proto\x12\vlinks_write\"\xba\x01\n" +
	"\x11CreateLinkRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x02 \x01(\tR\n" +
	"customSlug\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\x04 \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"\x9b\x02\n" +
	"\x12CreateLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x03 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x04 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\a \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\b \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"D\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\".\n" +
	"\x12DeleteLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x11UpdateLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12,\n" +
	"\x0fexpiration_date\x18\x05 \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"\xbe\x02\n" +
	"\x12UpdateLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\t \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\")\n" +
	"\x17UpdateLinkClicksRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc4\x02\n" +
	"\x18UpdateLinkClicksResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\t \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date2\xe9\x02\n" +
	"\x11LinksServiceWrite\x12O\n" +
	"\n" +
	"CreateLink\x12\x1e.links_write.CreateLinkRequest\x1a\x1f.links_write.CreateLinkResponse\"\x00\x12O\n" +
	"\n" +
	"DeleteLink\x12\x1e.links_write.DeleteLinkRequest\x1a\x1f.links_write.DeleteLinkResponse\"\x00\x12O\n" +
	"\n" +
	"UpdateLink\x12\x1e.links_write.UpdateLinkRequest\x1a\x1f.links_write.UpdateLinkResponse\"\x00\x12a\n" +
	"\x10UpdateLinkClicks\x12$.links_write.UpdateLinkClicksRequest\x1a%.links_write.UpdateLinkClicksResponse\"\x00B\x15Z\x13links-service/protob\x06proto3"

var (
	file_proto_links_write_proto_rawDescOnce sync.Once
	file_proto_links_write_proto_rawDescData []byte
)

func file_proto_links_write_proto_rawDescGZIP() []byte {
	file_proto_links_write_proto_rawDescOnce.Do(func() {
		file_proto_links_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_links_write_proto_rawDesc), len(file_proto_links_write_proto_rawDesc)))
	})
	return file_proto_links_write_proto_rawDescData
}

var file_proto_links_write_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_links_write_proto_goTypes = []any{
	(*CreateLinkRequest)(nil),        // 0: links_write.CreateLinkRequest
	(*CreateLinkResponse)(nil),       // 1: links_write.CreateLinkResponse
	(*DeleteLinkRequest)(nil),        // 2: links_write.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),       // 3: links_write.DeleteLinkResponse
	(*UpdateLinkRequest)(nil),        // 4: links_write.UpdateLinkRequest
	(*UpdateLinkResponse)(nil),       // 5: links_write.UpdateLinkResponse
	(*UpdateLinkClicksRequest)(nil),  // 6: links_write.UpdateLinkClicksRequest
	(*UpdateLinkClicksResponse)(nil), // 7: links_write.UpdateLinkClicksResponse
}
var file_proto_links_write_proto_depIdxs = []int32{
	0, // 0: links_write.LinksServiceWrite.CreateLink:input_type -> links_write.CreateLinkRequest
	2, // 1: links_write.LinksServiceWrite.DeleteLink:input_type -> links_write.DeleteLinkRequest
	4, // 2: links_write.LinksServiceWrite.UpdateLink:input_type -> links_write.UpdateLinkRequest
	6, // 3: links_write.LinksServiceWrite.UpdateLinkClicks:input_type -> links_write.UpdateLinkClicksRequest
	1, // 4: links_write.LinksServiceWrite.CreateLink:output_type -> links_write.CreateLinkResponse
	3, // 5: links_write.LinksServiceWrite.DeleteLink:output_type -> links_write.DeleteLinkResponse
	5, // 6: links_write.LinksServiceWrite.UpdateLink:output_type -> links_write.UpdateLinkResponse
	7, // 7: links_write.LinksServiceWrite.UpdateLinkClicks:output_type -> links_write.UpdateLinkClicksResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_links_write_proto_init() }
func file_proto_links_write_proto_init() {
	if File_proto_links_write_proto != nil {
		return
	}
	file_proto_links_write_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_links_write_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_links_write_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_links_write_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_links_write_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_links_write_proto_rawDesc), len(file_proto_links_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_links_write_proto_goTypes,
		DependencyIndexes: file_proto_links_write_proto_depIdxs,
		MessageInfos:      file_proto_links_write_proto_msgTypes,
	}.Build()
	File_proto_links_write_proto = out.File
	file_proto_links_write_proto_goTypes = nil
	file_proto_links_write_proto_depIdxs = nil
}
