// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/links_read.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_proto_links_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_read_proto_rawDescGZIP(), []int{0}
}

func (x *GetLinkRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetLinkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,8,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_proto_links_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_read_proto_rawDescGZIP(), []int{1}
}

func (x *GetLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetLinkResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *GetLinkResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *GetLinkResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetLinkResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetLinkResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type GetCustomerLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	SlugType      *string                `protobuf:"bytes,6,opt,name=slug_type,json=slugType,proto3,oneof" json:"slug_type,omitempty"`
	SortBy        *string                `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortDirection *string                `protobuf:"bytes,8,opt,name=sort_direction,json=sortDirection,proto3,oneof" json:"sort_direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerLinksRequest) Reset() {
	*x = GetCustomerLinksRequest{}
	mi := &file_proto_links_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerLinksRequest) ProtoMessage() {}

func (x *GetCustomerLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerLinksRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_read_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerLinksRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCustomerLinksRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetCustomerLinksRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetSlugType() string {
	if x != nil && x.SlugType != nil {
		return *x.SlugType
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetSortDirection() string {
	if x != nil && x.SortDirection != nil {
		return *x.SortDirection
	}
	return ""
}

type GetCustomerLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*GetLinkResponse     `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerLinksResponse) Reset() {
	*x = GetCustomerLinksResponse{}
	mi := &file_proto_links_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerLinksResponse) ProtoMessage() {}

func (x *GetCustomerLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerLinksResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerLinksResponse) GetLinks() []*GetLinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_proto_links_read_proto protoreflect.FileDescriptor

const file_proto_links_read_proto_rawDesc = "" +
	"\n" +
	"\x16proto/links_read.proto\x12\n" +
	"links_read\"-\n" +
	"\x0eGetLinkRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"\x9a\x02\n" +
	"\x0fGetLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12,\n" +
	"\x0fexpiration_date\x18\b \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"\xf0\x02\n" +
	"\x17GetCustomerLinksRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x03R\x06status\x88\x01\x01\x12 \n" +
	"\tslug_type\x18\x06 \x01(\tH\x04R\bslugType\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\a \x01(\tH\x05R\x06sortBy\x88\x01\x01\x12*\n" +
	"\x0esort_direction\x18\b \x01(\tH\x06R\rsortDirection\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_searchB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_slug_typeB\n" +
	"\n" +
	"\b_sort_byB\x11\n" +
	"\x0f_sort_direction\"M\n" +
	"\x18GetCustomerLinksResponse\x121\n" +
	"\x05links\x18\x01 \x03(\v2\x1b.links_read.GetLinkResponseR\x05links2\xb9\x01\n" +
	"\x10LinksServiceRead\x12D\n" +
	"\aGetLink\x12\x1a.links_read.GetLinkRequest\x1a\x1b.links_read.GetLinkResponse\"\x00\x12_\n" +
	"\x10GetCustomerLinks\x12#.links_read.GetCustomerLinksRequest\x1a$.links_read.GetCustomerLinksResponse\"\x00B\x15Z\x13links-service/protob\x06proto3"

var (
	file_proto_links_read_proto_rawDescOnce sync.Once
	file_proto_links_read_proto_rawDescData []byte
)

func file_proto_links_read_proto_rawDescGZIP() []byte {
	file_proto_links_read_proto_rawDescOnce.Do(func() {
		file_proto_links_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_links_read_proto_rawDesc), len(file_proto_links_read_proto_rawDesc)))
	})
	return file_proto_links_read_proto_rawDescData
}

var file_proto_links_read_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_links_read_proto_goTypes = []any{
	(*GetLinkRequest)(nil),           // 0: links_read.GetLinkRequest
	(*GetLinkResponse)(nil),          // 1: links_read.GetLinkResponse
	(*GetCustomerLinksRequest)(nil),  // 2: links_read.GetCustomerLinksRequest
	(*GetCustomerLinksResponse)(nil), // 3: links_read.GetCustomerLinksResponse
}
var file_proto_links_read_proto_depIdxs = []int32{
	1, // 0: links_read.GetCustomerLinksResponse.links:type_name -> links_read.GetLinkResponse
	0, // 1: links_read.LinksServiceRead.GetLink:input_type -> links_read.GetLinkRequest
	2, // 2: links_read.LinksServiceRead.GetCustomerLinks:input_type -> links_read.GetCustomerLinksRequest
	1, // 3: links_read.LinksServiceRead.GetLink:output_type -> links_read.GetLinkResponse
	3, // 4: links_read.LinksServiceRead.GetCustomerLinks:output_type -> links_read.GetCustomerLinksResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_links_read_proto_init() }
func file_proto_links_read_proto_init() {
	if File_proto_links_read_proto != nil {
		return
	}
	file_proto_links_read_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_links_read_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_links_read_proto_rawDesc), len(file_proto_links_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_links_read_proto_goTypes,
		DependencyIndexes: file_proto_links_read_proto_depIdxs,
		MessageInfos:      file_proto_links_read_proto_msgTypes,
	}.Build()
	File_proto_links_read_proto = out.File
	file_proto_links_read_proto_goTypes = nil
	file_proto_links_read_proto_depIdxs = nil
}
