// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          pgtype.UUID        `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortUrl    string             `json:"short_url"`
	CustomSlug  pgtype.Text        `json:"custom_slug"`
	Clicks      int32              `json:"clicks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
}
