// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateCustomer(ctx context.Context, id pgtype.UUID) (Customer, error)
	ActivateCustomerByEmail(ctx context.Context, email string) (Customer, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, id pgtype.UUID) (int64, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	HasActiveCustomer(ctx context.Context, arg HasActiveCustomerParams) (bool, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Customer, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
