// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/links.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl    string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,2,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	CustomerId     string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_proto_links_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *CreateLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateLinkRequest) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type CreateLinkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,3,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,4,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId     string                 `protobuf:"bytes,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,8,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_proto_links_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateLinkResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *CreateLinkResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *CreateLinkResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateLinkResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateLinkResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateLinkResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_proto_links_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{2}
}

func (x *GetLinkRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetLinkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,8,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_proto_links_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{3}
}

func (x *GetLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetLinkResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *GetLinkResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *GetLinkResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetLinkResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetLinkResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type GetCustomerLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	SlugType      *string                `protobuf:"bytes,6,opt,name=slug_type,json=slugType,proto3,oneof" json:"slug_type,omitempty"`
	SortBy        *string                `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortDirection *string                `protobuf:"bytes,8,opt,name=sort_direction,json=sortDirection,proto3,oneof" json:"sort_direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerLinksRequest) Reset() {
	*x = GetCustomerLinksRequest{}
	mi := &file_proto_links_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerLinksRequest) ProtoMessage() {}

func (x *GetCustomerLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerLinksRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerLinksRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerLinksRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetCustomerLinksRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetCustomerLinksRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetSlugType() string {
	if x != nil && x.SlugType != nil {
		return *x.SlugType
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *GetCustomerLinksRequest) GetSortDirection() string {
	if x != nil && x.SortDirection != nil {
		return *x.SortDirection
	}
	return ""
}

type GetCustomerLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*GetLinkResponse     `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerLinksResponse) Reset() {
	*x = GetCustomerLinksResponse{}
	mi := &file_proto_links_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerLinksResponse) ProtoMessage() {}

func (x *GetCustomerLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerLinksResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerLinksResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerLinksResponse) GetLinks() []*GetLinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GetCustomerLinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_proto_links_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_proto_links_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,5,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_proto_links_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *UpdateLinkRequest) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type UpdateLinkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId     string                 `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,9,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkResponse) Reset() {
	*x = UpdateLinkResponse{}
	mi := &file_proto_links_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkResponse) ProtoMessage() {}

func (x *UpdateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UpdateLinkResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *UpdateLinkResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *UpdateLinkResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateLinkResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateLinkResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateLinkResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

type UpdateLinkClicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkClicksRequest) Reset() {
	*x = UpdateLinkClicksRequest{}
	mi := &file_proto_links_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkClicksRequest) ProtoMessage() {}

func (x *UpdateLinkClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkClicksRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkClicksRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLinkClicksRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateLinkClicksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl    string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl       string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	CustomSlug     string                 `protobuf:"bytes,4,opt,name=custom_slug,json=customSlug,proto3" json:"custom_slug,omitempty"`
	Clicks         int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerId     string                 `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ExpirationDate *string                `protobuf:"bytes,9,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkClicksResponse) Reset() {
	*x = UpdateLinkClicksResponse{}
	mi := &file_proto_links_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkClicksResponse) ProtoMessage() {}

func (x *UpdateLinkClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkClicksResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkClicksResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLinkClicksResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetCustomSlug() string {
	if x != nil {
		return x.CustomSlug
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *UpdateLinkClicksResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateLinkClicksResponse) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

var File_proto_links_proto protoreflect.FileDescriptor

const file_proto_links_proto_rawDesc = "" +
	"\n" +
	"\x11proto/links.proto\x12\x05links\"\xba\x01\n" +
	"\x11CreateLinkRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x02 \x01(\tR\n" +
	"customSlug\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\x04 \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"\x9b\x02\n" +
	"\x12CreateLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x03 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x04 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\a \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\b \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"-\n" +
	"\x0eGetLinkRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"\x9a\x02\n" +
	"\x0fGetLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12,\n" +
	"\x0fexpiration_date\x18\b \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"\xf0\x02\n" +
	"\x17GetCustomerLinksRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x03R\x06status\x88\x01\x01\x12 \n" +
	"\tslug_type\x18\x06 \x01(\tH\x04R\bslugType\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\a \x01(\tH\x05R\x06sortBy\x88\x01\x01\x12*\n" +
	"\x0esort_direction\x18\b \x01(\tH\x06R\rsortDirection\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_searchB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_slug_typeB\n" +
	"\n" +
	"\b_sort_byB\x11\n" +
	"\x0f_sort_direction\"^\n" +
	"\x18GetCustomerLinksResponse\x12,\n" +
	"\x05links\x18\x01 \x03(\v2\x16.links.GetLinkResponseR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"D\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\".\n" +
	"\x12DeleteLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x11UpdateLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12,\n" +
	"\x0fexpiration_date\x18\x05 \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\"\xbe\x02\n" +
	"\x12UpdateLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\t \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date\")\n" +
	"\x17UpdateLinkClicksRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc4\x02\n" +
	"\x18UpdateLinkClicksResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vcustom_slug\x18\x04 \x01(\tR\n" +
	"customSlug\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\tR\n" +
	"customerId\x12,\n" +
	"\x0fexpiration_date\x18\t \x01(\tH\x00R\x0eexpirationDate\x88\x01\x01B\x12\n" +
	"\x10_expiration_date2\xc7\x03\n" +
	"\fLinksService\x12C\n" +
	"\n" +
	"CreateLink\x12\x18.links.CreateLinkRequest\x1a\x19.links.CreateLinkResponse\"\x00\x12:\n" +
	"\aGetLink\x12\x15.links.GetLinkRequest\x1a\x16.links.GetLinkResponse\"\x00\x12U\n" +
	"\x10GetCustomerLinks\x12\x1e.links.GetCustomerLinksRequest\x1a\x1f.links.GetCustomerLinksResponse\"\x00\x12C\n" +
	"\n" +
	"DeleteLink\x12\x18.links.DeleteLinkRequest\x1a\x19.links.DeleteLinkResponse\"\x00\x12C\n" +
	"\n" +
	"UpdateLink\x12\x18.links.UpdateLinkRequest\x1a\x19.links.UpdateLinkResponse\"\x00\x12U\n" +
	"\x10UpdateLinkClicks\x12\x1e.links.UpdateLinkClicksRequest\x1a\x1f.links.UpdateLinkClicksResponse\"\x00B\x15Z\x13links-service/protob\x06proto3"

var (
	file_proto_links_proto_rawDescOnce sync.Once
	file_proto_links_proto_rawDescData []byte
)

func file_proto_links_proto_rawDescGZIP() []byte {
	file_proto_links_proto_rawDescOnce.Do(func() {
		file_proto_links_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_links_proto_rawDesc), len(file_proto_links_proto_rawDesc)))
	})
	return file_proto_links_proto_rawDescData
}

var file_proto_links_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_links_proto_goTypes = []any{
	(*CreateLinkRequest)(nil),        // 0: links.CreateLinkRequest
	(*CreateLinkResponse)(nil),       // 1: links.CreateLinkResponse
	(*GetLinkRequest)(nil),           // 2: links.GetLinkRequest
	(*GetLinkResponse)(nil),          // 3: links.GetLinkResponse
	(*GetCustomerLinksRequest)(nil),  // 4: links.GetCustomerLinksRequest
	(*GetCustomerLinksResponse)(nil), // 5: links.GetCustomerLinksResponse
	(*DeleteLinkRequest)(nil),        // 6: links.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),       // 7: links.DeleteLinkResponse
	(*UpdateLinkRequest)(nil),        // 8: links.UpdateLinkRequest
	(*UpdateLinkResponse)(nil),       // 9: links.UpdateLinkResponse
	(*UpdateLinkClicksRequest)(nil),  // 10: links.UpdateLinkClicksRequest
	(*UpdateLinkClicksResponse)(nil), // 11: links.UpdateLinkClicksResponse
}
var file_proto_links_proto_depIdxs = []int32{
	3,  // 0: links.GetCustomerLinksResponse.links:type_name -> links.GetLinkResponse
	0,  // 1: links.LinksService.CreateLink:input_type -> links.CreateLinkRequest
	2,  // 2: links.LinksService.GetLink:input_type -> links.GetLinkRequest
	4,  // 3: links.LinksService.GetCustomerLinks:input_type -> links.GetCustomerLinksRequest
	6,  // 4: links.LinksService.DeleteLink:input_type -> links.DeleteLinkRequest
	8,  // 5: links.LinksService.UpdateLink:input_type -> links.UpdateLinkRequest
	10, // 6: links.LinksService.UpdateLinkClicks:input_type -> links.UpdateLinkClicksRequest
	1,  // 7: links.LinksService.CreateLink:output_type -> links.CreateLinkResponse
	3,  // 8: links.LinksService.GetLink:output_type -> links.GetLinkResponse
	5,  // 9: links.LinksService.GetCustomerLinks:output_type -> links.GetCustomerLinksResponse
	7,  // 10: links.LinksService.DeleteLink:output_type -> links.DeleteLinkResponse
	9,  // 11: links.LinksService.UpdateLink:output_type -> links.UpdateLinkResponse
	11, // 12: links.LinksService.UpdateLinkClicks:output_type -> links.UpdateLinkClicksResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_links_proto_init() }
func file_proto_links_proto_init() {
	if File_proto_links_proto != nil {
		return
	}
	file_proto_links_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_links_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_links_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_links_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_links_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_links_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_links_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_links_proto_rawDesc), len(file_proto_links_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_links_proto_goTypes,
		DependencyIndexes: file_proto_links_proto_depIdxs,
		MessageInfos:      file_proto_links_proto_msgTypes,
	}.Build()
	File_proto_links_proto = out.File
	file_proto_links_proto_goTypes = nil
	file_proto_links_proto_depIdxs = nil
}
