name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI_ENV: ${{ secrets.CI_ENV }}
      DB_SOURCE: ${{ secrets.DB_SOURCE }}
      MASTER_KEY: ${{ secrets.MASTER_KEY }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      TWILIO_USERNAME: ${{ secrets.TWILIO_USERNAME }}
      TWILIO_PASSWORD: ${{ secrets.TWILIO_PASSWORD }}
      TWILIO_VERIFICATION_SERVICE: ${{ secrets.TWILIO_VERIFICATION_SERVICE }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Test
      run: make testsci
      working-directory: ./auth-service
