name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_SOURCE: ${{ secrets.DB_SOURCE }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      MASTER_KEY: ${{ secrets.MASTER_KEY }}
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
      FRONTEND_SOURCE: ${{ secrets.FRONTEND_SOURCE }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      NEXT_PUBLIC_MASTER_KEY: ${{ secrets.NEXT_PUBLIC_MASTER_KEY }}
      NEXT_PUBLIC_AUTH_SERVICE_API: ${{ secrets.NEXT_PUBLIC_AUTH_SERVICE_API }}    

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Test
      run: make test
      working-directory: ./auth-service