name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432   
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      CI_ENV: ${{ secrets.CI_ENV }}
      DB_SOURCE: ${{ secrets.DB_SOURCE }}
      MASTER_KEY: ${{ secrets.MASTER_KEY }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      TWILIO_USERNAME: ${{ secrets.TWILIO_USERNAME }}
      TWILIO_PASSWORD: ${{ secrets.TWILIO_PASSWORD }}
      TWILIO_VERIFICATION_SERVICE: ${{ secrets.TWILIO_VERIFICATION_SERVICE }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Install golang-migrate
      run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

    - name: Run migrations
      run: make migrateup
      working-directory: ./auth-service

    - name: Test
      run: make testsci
      working-directory: ./auth-service
